<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>03-Register with a different valid email</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dc0f4826-73bf-4ed5-9e0e-837f06f1f11f</testSuiteGuid>
   <testCaseLink>
      <guid>aa3f73b3-ba9b-41f1-99e7-adbf76c8823d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REGISTRATION/00-Registration</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Test1&quot;</value>
         <variableId>8f00f16c-9091-4536-bb17-b2b4095237b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;8123456789&quot;</value>
         <variableId>dac8fd6a-b1fe-4607-951e-e3392c7ab1d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Test Store 1&quot;</value>
         <variableId>50d1bba1-e0d8-410c-b4c0-b61e8b4c2595</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;distributor&quot;</value>
         <variableId>2970fd92-fecc-425f-acad-b94602f97cc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Password123&quot;</value>
         <variableId>3f344011-2cb6-430e-b113-e9dce93fc0dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Password123&quot;</value>
         <variableId>1c7b2fd6-2f04-4f18-a1ba-69e97c13834b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
