<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Kata Sandi_isTncChecked</name>
   <tag></tag>
   <elementGuidId>19d4974d-531b-4cbb-8fe5-c1c0438003d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register__checkbox__tnc']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @data-testid = 'register__checkbox__tnc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register__checkbox__tnc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2105b55e-949e-4dcf-b54d-a160c984833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register__checkbox__tnc</value>
      <webElementGuid>143338f9-b83d-4b9e-ad1b-faba732ac88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>ea5ca2d4-f2f2-4a51-92a1-7a6b1406a8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isTncChecked</value>
      <webElementGuid>1d3d0e52-4619-4af5-832e-0032edb9d49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>acf79d87-2eae-4155-887e-6d1050cfe39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-blue-B700 border-neutral-N400 h-5 w-5 cursor-pointer rounded border-2 focus:outline-0 focus:ring-transparent disabled:text-neutral-N200 disabled:border-neutral-N200 disabled:cursor-not-allowed checked:disabled:text-blue-B400 checked:disabled:border-blue-B400 indeterminate:disabled:text-blue-B400 indeterminate:disabled:border-blue-B400</value>
      <webElementGuid>12d3a8c6-c71e-4ebb-a984-668a72ad17b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__checkbox__tnc</value>
      <webElementGuid>0b0dc298-a96d-478d-9bc3-202f051f9064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register__checkbox__tnc&quot;)</value>
      <webElementGuid>919e4a99-476b-4e27-8e3d-20309c8fca25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register__checkbox__tnc']</value>
      <webElementGuid>e88eefb7-1741-4811-a866-9f82868c3848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[8]/div/input</value>
      <webElementGuid>1b8ecf3b-5f0a-4c75-b20e-7ae92137c7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>46bd9d8e-46b1-491d-82ca-984e080f1e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'register__checkbox__tnc' and @name = 'isTncChecked' and @type = 'checkbox']</value>
      <webElementGuid>6f00c287-5ed0-4585-bfd9-4975b9299fc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
