<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata Sandi_confirmPassword</name>
   <tag></tag>
   <elementGuidId>fca1cf93-e6ff-439e-8ce7-cae9b980a9f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-:Rf6l6:']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'password' and @name = 'confirmPassword' and @data-testid = 'register__text-field__confirm-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a74bad1f-db85-4025-9cf7-ac5005a5da37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f5b52c82-d29b-4a40-83a6-3abc1107b842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>821153f7-0888-47ac-b084-8f4404cd4549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>0276dc73-a3bc-4524-a1ca-29ddcff42e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-:Rf6l6:</value>
      <webElementGuid>122e1e30-cb04-400c-845a-a550a2d9e9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>placeholder</value>
      <webElementGuid>11cd8d6e-857b-46b2-be22-6fdfa54315a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-disabled border-neutral-N300 enabled:text-he disabled:border-neutral-N300 peer block w-full rounded border p-4 text-base leading-6 placeholder-transparent enabled:focus:outline-none enabled:focus:ring-1 disabled:cursor-not-allowed pr-12 enabled:focus:border-blue-B700 enabled:focus:ring-blue-B700</value>
      <webElementGuid>25b1b15c-6d16-4220-a378-ec9a64c4a610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8df22eb1-e018-4c4e-bdac-613e5120e1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__text-field__confirm-password</value>
      <webElementGuid>037a9061-4e6b-4f92-a667-cf66ef2c9ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-:Rf6l6:&quot;)</value>
      <webElementGuid>e44d0c83-6cde-480f-ab0b-38710086694c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-:Rf6l6:']</value>
      <webElementGuid>b6c047b2-73cf-4bfc-8cf9-80fc264accd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[7]/div/input</value>
      <webElementGuid>4fbaa4bf-046f-448c-828c-81d9a5f9dd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>628633d6-9a51-4c14-8d43-faf880949872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirmPassword' and @id = 'input-:Rf6l6:' and @placeholder = 'placeholder']</value>
      <webElementGuid>d4910fdc-8eb3-4f5f-b91a-a9e16b033614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
