<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tipe Bisnis_businessType</name>
   <tag></tag>
   <elementGuidId>d401217e-d177-4e1f-a93c-2d4adc0f0def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='distributor-:R696l6:']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'businessType' and @data-testid = 'register__radio-button__${businesstype}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71c8e048-ba64-4058-bd1b-7d1c26f70ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a0b696c2-c24e-4788-9005-8c28d2e782f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessType</value>
      <webElementGuid>41fe5aa7-e15a-4eae-9b5e-e21965e8b3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>distributor-:R696l6:</value>
      <webElementGuid>3833b18e-7c11-449f-a5f4-315cd32e3c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-neutral-N400 enabled:checked:text-blue-B700 h-4 w-4 border-2 enabled:focus:ring-0 enabled:focus:ring-offset-0 disabled:bg-neutral-N100 disabled:cursor-not-allowed checked:disabled:bg-blue-B400 checked:disabled:hover:bg-blue-B400</value>
      <webElementGuid>7df0ecfe-2fe1-44b2-bf99-4b1dae811897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>register__radio-button__${businesstype}</value>
      <webElementGuid>80a0f5a1-6a42-419b-84d0-43c9e0f8f510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>distributor</value>
      <webElementGuid>3aa15a93-67cd-4f44-83ab-b926549995bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;distributor-:R696l6:&quot;)</value>
      <webElementGuid>4ac37938-14e5-4295-93de-95ef88f0c05d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='distributor-:R696l6:']</value>
      <webElementGuid>2d07e29a-5a55-417e-be52-300713d868f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/form/div[4]/div[2]/div/input</value>
      <webElementGuid>4f745fac-3dc6-416c-a26c-3fd9e7f22a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e51da5e6-20f2-410d-b5c1-ac76d554bea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'businessType' and @id = 'distributor-:R696l6:']</value>
      <webElementGuid>de74698f-a3a0-4ec2-a05b-7f9ec1131ddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
